import type { Metadata } from 'next';

export const SITE_URL = 'https://olhaip.com';
export const SITE_NAME = 'OlhaIP';

// Generated by src/app/opengraph-image.tsx. Pages that define their own
// openGraph/twitter metadata do not inherit that file-based image, so it is
// referenced explicitly here.
const SOCIAL_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'OlhaIP - See what the internet sees',
};

interface PageMetadataOptions {
  /** Full page title, e.g. "DNS Lookup Tool | OlhaIP" */
  title: string;
  /** Meta description, ideally 110-160 characters */
  description: string;
  /** Path of the page, e.g. "/dns-lookup". Used for the canonical URL and og:url. */
  path: string;
  type?: 'website' | 'article';
}

/**
 * Builds the metadata for a page: title, description, canonical URL and
 * matching Open Graph / Twitter tags. Relative URLs are resolved against
 * `metadataBase`, which is set in the root layout.
 */
export function buildMetadata({
  title,
  description,
  path,
  type = 'website',
}: PageMetadataOptions): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title,
      description,
      url: path,
      siteName: SITE_NAME,
      type,
      locale: 'en_US',
      images: [SOCIAL_IMAGE],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [SOCIAL_IMAGE.url],
    },
  };
}

/** Strips the " | OlhaIP" suffix from a page title. */
export function baseTitle(title: string): string {
  return title.replace(/\s*[|-]\s*OlhaIP$/, '');
}
